from model.domain.instanceRepository import InstanceRepository
from q_learning.learningModule import LearningModule

if __name__ == "__main__":
    # Start server
    # api = Server(9876)
    instances = [
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 43,
         'ninetyFivePercentileResponseTime': 188, 'failedRequestPercentage': 0, 'load': 20},
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 763,
         'ninetyFivePercentileResponseTime': 4111, 'failedRequestPercentage': 0, 'load': 38},
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 162,
         'ninetyFivePercentileResponseTime': 866, 'failedRequestPercentage': 0, 'load': 56},
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 156,
         'ninetyFivePercentileResponseTime': 717, 'failedRequestPercentage': 0, 'load': 74},
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 574,
         'ninetyFivePercentileResponseTime': 1398, 'failedRequestPercentage': 0, 'load': 92},
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 1249,
         'ninetyFivePercentileResponseTime': 2418, 'failedRequestPercentage': 0, 'load': 110},
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 3804,
         'ninetyFivePercentileResponseTime': 5599, 'failedRequestPercentage': 0, 'load': 128},
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 12102,
         'ninetyFivePercentileResponseTime': 21217, 'failedRequestPercentage': 0, 'load': 146},
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 10969,
         'ninetyFivePercentileResponseTime': 25377, 'failedRequestPercentage': 0, 'load': 164},
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 29521,
         'ninetyFivePercentileResponseTime': 57799, 'failedRequestPercentage': 0, 'load': 182},
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 34085,
         'ninetyFivePercentileResponseTime': 60002, 'failedRequestPercentage': 37, 'load': 200},
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 41071,
         'ninetyFivePercentileResponseTime': 60002, 'failedRequestPercentage': 84, 'load': 218},
        {'instanceName': 'high-mem-high-cpu', 'instanceCPUs': 3, 'instanceMemory': 1000, 'meanResponseTime': 23403,
         'ninetyFivePercentileResponseTime': 60002, 'failedRequestPercentage': 100, 'load': 236},
        {'instanceName': 'medium-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 800, 'meanResponseTime': 108,
         'ninetyFivePercentileResponseTime': 893, 'failedRequestPercentage': 0, 'load': 20},
        {'instanceName': 'medium-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 800, 'meanResponseTime': 637,
         'ninetyFivePercentileResponseTime': 2181, 'failedRequestPercentage': 0, 'load': 28},
        {'instanceName': 'medium-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 800, 'meanResponseTime': 2350,
         'ninetyFivePercentileResponseTime': 4207, 'failedRequestPercentage': 0, 'load': 36},
        {'instanceName': 'medium-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 800, 'meanResponseTime': 2360,
         'ninetyFivePercentileResponseTime': 3439, 'failedRequestPercentage': 0, 'load': 44},
        {'instanceName': 'medium-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 800, 'meanResponseTime': 7405,
         'ninetyFivePercentileResponseTime': 12185, 'failedRequestPercentage': 0, 'load': 52},
        {'instanceName': 'medium-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 800, 'meanResponseTime': 7976,
         'ninetyFivePercentileResponseTime': 13206, 'failedRequestPercentage': 0, 'load': 60},
        {'instanceName': 'medium-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 800, 'meanResponseTime': 13428,
         'ninetyFivePercentileResponseTime': 23972, 'failedRequestPercentage': 0, 'load': 68},
        {'instanceName': 'medium-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 800, 'meanResponseTime': 19698,
         'ninetyFivePercentileResponseTime': 34498, 'failedRequestPercentage': 0, 'load': 76},
        {'instanceName': 'medium-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 800, 'meanResponseTime': 23726,
         'ninetyFivePercentileResponseTime': 44261, 'failedRequestPercentage': 0, 'load': 84},
        {'instanceName': 'medium-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 800, 'meanResponseTime': 30374,
         'ninetyFivePercentileResponseTime': 56438, 'failedRequestPercentage': 0, 'load': 92},
        {'instanceName': 'medium-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 800, 'meanResponseTime': 37539,
         'ninetyFivePercentileResponseTime': 60002, 'failedRequestPercentage': 25, 'load': 100},
        {'instanceName': 'low-mem-medium-cpu', 'instanceCPUs': 2, 'instanceMemory': 400, 'meanResponseTime': 27,
         'ninetyFivePercentileResponseTime': 88, 'failedRequestPercentage': 0, 'load': 20},
        {'instanceName': 'low-mem-medium-cpu', 'instanceCPUs': 2, 'instanceMemory': 400, 'meanResponseTime': 47,
         'ninetyFivePercentileResponseTime': 328, 'failedRequestPercentage': 0, 'load': 28},
        {'instanceName': 'low-mem-medium-cpu', 'instanceCPUs': 2, 'instanceMemory': 400, 'meanResponseTime': 89,
         'ninetyFivePercentileResponseTime': 598, 'failedRequestPercentage': 0, 'load': 36},
        {'instanceName': 'low-mem-medium-cpu', 'instanceCPUs': 2, 'instanceMemory': 400, 'meanResponseTime': 113,
         'ninetyFivePercentileResponseTime': 675, 'failedRequestPercentage': 0, 'load': 44},
        {'instanceName': 'low-mem-medium-cpu', 'instanceCPUs': 2, 'instanceMemory': 400, 'meanResponseTime': 219,
         'ninetyFivePercentileResponseTime': 917, 'failedRequestPercentage': 0, 'load': 52},
        {'instanceName': 'low-mem-medium-cpu', 'instanceCPUs': 2, 'instanceMemory': 400, 'meanResponseTime': 1413,
         'ninetyFivePercentileResponseTime': 3706, 'failedRequestPercentage': 0, 'load': 60},
        {'instanceName': 'low-mem-medium-cpu', 'instanceCPUs': 2, 'instanceMemory': 400, 'meanResponseTime': 4182,
         'ninetyFivePercentileResponseTime': 9197, 'failedRequestPercentage': 0, 'load': 68},
        {'instanceName': 'low-mem-medium-cpu', 'instanceCPUs': 2, 'instanceMemory': 400, 'meanResponseTime': 12040,
         'ninetyFivePercentileResponseTime': 25669, 'failedRequestPercentage': 0, 'load': 76},
        {'instanceName': 'low-mem-medium-cpu', 'instanceCPUs': 2, 'instanceMemory': 400, 'meanResponseTime': 22757,
         'ninetyFivePercentileResponseTime': 49400, 'failedRequestPercentage': 2, 'load': 84},
        {'instanceName': 'low-mem-medium-cpu', 'instanceCPUs': 2, 'instanceMemory': 400, 'meanResponseTime': 34416,
         'ninetyFivePercentileResponseTime': 60003, 'failedRequestPercentage': 41, 'load': 92},
        {'instanceName': 'low-mem-medium-cpu', 'instanceCPUs': 2, 'instanceMemory': 400, 'meanResponseTime': 44019,
         'ninetyFivePercentileResponseTime': 60003, 'failedRequestPercentage': 90, 'load': 100},
        {'instanceName': 'low-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 400, 'meanResponseTime': 33,
         'ninetyFivePercentileResponseTime': 42, 'failedRequestPercentage': 0, 'load': 10},
        {'instanceName': 'low-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 400, 'meanResponseTime': 29,
         'ninetyFivePercentileResponseTime': 86, 'failedRequestPercentage': 0, 'load': 20},
        {'instanceName': 'low-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 400, 'meanResponseTime': 1027,
         'ninetyFivePercentileResponseTime': 3443, 'failedRequestPercentage': 0, 'load': 30},
        {'instanceName': 'low-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 400, 'meanResponseTime': 781,
         'ninetyFivePercentileResponseTime': 2016, 'failedRequestPercentage': 0, 'load': 40},
        {'instanceName': 'low-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 400, 'meanResponseTime': 10412,
         'ninetyFivePercentileResponseTime': 20615, 'failedRequestPercentage': 0, 'load': 50},
        {'instanceName': 'low-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 400, 'meanResponseTime': 26640,
         'ninetyFivePercentileResponseTime': 49803, 'failedRequestPercentage': 2, 'load': 60},
        {'instanceName': 'low-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 400, 'meanResponseTime': 26584,
         'ninetyFivePercentileResponseTime': 54098, 'failedRequestPercentage': 8, 'load': 70},
        {'instanceName': 'low-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 400, 'meanResponseTime': 36054,
         'ninetyFivePercentileResponseTime': 60002, 'failedRequestPercentage': 37, 'load': 80},
        {'instanceName': 'low-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 400, 'meanResponseTime': 45852,
         'ninetyFivePercentileResponseTime': 60002, 'failedRequestPercentage': 87, 'load': 90},
        {'instanceName': 'low-mem-low-cpu', 'instanceCPUs': 1, 'instanceMemory': 400, 'meanResponseTime': 29593,
         'ninetyFivePercentileResponseTime': 60002, 'failedRequestPercentage': 100, 'load': 100},
    ]

    for data in instances:
        InstanceRepository.instance().manage_new_instance(data)

    LearningModule.instance().start()
